language: python
python:
  - "3.8"      # current default Python on Travis CI
# command to run tests
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=data_structures tests/
  - pylint data_structures